### ISSUE TITLE
No fps gainz

### ISSUE THREAD

**Issue by lukakostic** [sugi-cho/Unity-ParticleSystem-GPUUpdate#1]
So i tested this 'gpu update' and i get actually worse fps than on normal unity cpu particles. So i can get ~100k particles with ~60fps but with gpu update script and all the colors and stuff its about 10 fps. Is my gpu just weak?

**Comment by lukakostic** [comment]
I made/edited some compute shaders and im getting great performance (5 mil particles) out of them so i dont think its my gpu's fault

**Comment by sugi-cho** [comment]
Yes!
this issue is already written in README.md. but Japanese..(._.)
I tested same update with GPU vs CPU, and case of mass particles, GPU solution is not so good

(Google Translated)
Processing per ParticleSystem.GetParticles (particles), ParticleSystem.SetParticles (particles), ComputeBuffer.SetData (particles), ComputeBuffer.GetData (particles) seems to become heavier as the number of particles increases. The current situation makes me feel unusable.

Getting GPU Data from CPU is slow. and it is a bottleneck!

I hope there is something that can set particle data directly from ComputeBuffer to Unity ParticleSystem

so, this repo is not for someone need mass particles.this repo just update ParticleSystem with GPU
thank you!

**Comment by sugi-cho** [comment]
you need to create GPU-ParticleSystem.
